/// @file   Global_define.h
/// @date
/// @author Jaejin Ham
/// @brief  header들을 include하기 위한 통합 header파일

#ifndef __GLOBAL_HEADER_H__
#define __GLOBAL_HEADER_H__

// headers generated by code generator
#include "r_cg_macrodriver.h"
#include "r_cg_adc.h"
#include "r_cg_cgc.h"
#include "r_cg_intc.h"
#include "r_cg_port.h"
#include "r_cg_serial.h"
#include "r_cg_timer.h"
#include "r_cg_wdt.h"
#include "r_cg_userdefine.h"


// header generated by user
#include "Type_define.h"
#include "User_define.h"
#include "Lib_ADConvert.h"
#include "Lib_TimeScheduler.h"
#include "Lib_OperationMode.h"
#include "User_Main.h"
#include "WIFI_Config.h"


// library headers
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <math.h>


#endif

